// hospital-frontend/src/pages/Contact.jsx
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Mail, Phone, MapPin, Clock, Send, CheckCircle, AlertCircle } from 'lucide-react';
import { submitLead } from '../services/api';
import { Link } from 'react-router-dom';

export default function Contact({ hospital }) {
    const [formData, setFormData] = useState({
        name: '',
        email: '',
        phone: '',
        message: ''
    });
    const [loading, setLoading] = useState(false);
    const [status, setStatus] = useState(null); // 'success' | 'error' | null

    const handleChange = (e) => {
        const { name, value } = e.target;
        // Enforce max length limits
        const maxLengths = { name: 100, email: 254, phone: 20, message: 2000 };
        if (maxLengths[name] && value.length > maxLengths[name]) return;
        setFormData({ ...formData, [name]: value });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        // Client-side validation
        if (!formData.name.trim() || !formData.phone.trim() || !formData.message.trim()) {
            setStatus('error');
            return;
        }
        setLoading(true);
        setStatus(null);

        try {
            await submitLead({
                name: formData.name.trim(),
                email: formData.email.trim(),
                phone: formData.phone.trim(),
                message: formData.message.trim(),
                hospital_id: hospital?.id,
                source_url: window.location.pathname
            });
            setStatus('success');
            setFormData({ name: '', email: '', phone: '', message: '' });
        } catch (error) {
            if (import.meta.env.DEV) {
                console.error('Error submitting form:', error);
            }
            setStatus('error');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div>
            {/* Hero Section */}
            <section className="relative pt-32 pb-20 bg-gradient-to-br from-gray-50 via-white to-primary-50">
                <div className="container-custom">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                        className="text-center max-w-3xl mx-auto"
                    >
                        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
                            Contact <span className="text-gradient">Us</span>
                        </h1>
                        <p className="text-xl text-gray-600">
                            Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.
                        </p>
                    </motion.div>
                </div>
            </section>

            {/* Contact Content */}
            <section className="py-20 bg-white">
                <div className="container-custom">
                    <div className="grid lg:grid-cols-2 gap-12">
                        {/* Contact Form */}
                        <motion.div
                            initial={{ opacity: 0, x: -20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                        >
                            <div className="bg-gray-50 rounded-2xl p-8">
                                <h2 className="text-2xl font-bold text-gray-900 mb-6">Send us a Message</h2>

                                {status === 'success' && (
                                    <div className="bg-green-50 border border-green-200 rounded-lg p-4 mb-6 flex items-start gap-3">
                                        <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                                        <div>
                                            <p className="font-medium text-green-800">Message Sent Successfully!</p>
                                            <p className="text-sm text-green-700">We'll get back to you soon.</p>
                                        </div>
                                    </div>
                                )}

                                {status === 'error' && (
                                    <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6 flex items-start gap-3">
                                        <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                                        <div>
                                            <p className="font-medium text-red-800">Something went wrong!</p>
                                            <p className="text-sm text-red-700">Please try again or call us directly.</p>
                                        </div>
                                    </div>
                                )}

                                <form onSubmit={handleSubmit} className="space-y-6">
                                    <div>
                                        <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">
                                            Full Name *
                                        </label>
                                        <input
                                            type="text"
                                            id="name"
                                            name="name"
                                            value={formData.name}
                                            onChange={handleChange}
                                            required
                                            className="w-full px-4 py-3 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                                            placeholder="Your full name"
                                        />
                                    </div>

                                    <div>
                                        <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
                                            Email Address
                                        </label>
                                        <input
                                            type="email"
                                            id="email"
                                            name="email"
                                            value={formData.email}
                                            onChange={handleChange}
                                            className="w-full px-4 py-3 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                                            placeholder="your@email.com"
                                        />
                                    </div>

                                    <div>
                                        <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-2">
                                            Phone Number *
                                        </label>
                                        <input
                                            type="tel"
                                            id="phone"
                                            name="phone"
                                            value={formData.phone}
                                            onChange={handleChange}
                                            required
                                            className="w-full px-4 py-3 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                                            placeholder="+91 98765 43210"
                                        />
                                    </div>

                                    <div>
                                        <label htmlFor="message" className="block text-sm font-medium text-gray-700 mb-2">
                                            Message *
                                        </label>
                                        <textarea
                                            id="message"
                                            name="message"
                                            value={formData.message}
                                            onChange={handleChange}
                                            required
                                            rows={4}
                                            className="w-full px-4 py-3 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
                                            placeholder="How can we help you?"
                                        />
                                    </div>

                                    <button
                                        type="submit"
                                        disabled={loading}
                                        className="w-full btn-primary flex items-center justify-center gap-2"
                                    >
                                        {loading ? (
                                            <>
                                                <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent" />
                                                Sending...
                                            </>
                                        ) : (
                                            <>
                                                <Send className="w-5 h-5" />
                                                Send Message
                                            </>
                                        )}
                                    </button>
                                </form>
                            </div>
                        </motion.div>

                        {/* Contact Info & Map */}
                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="space-y-8"
                        >
                            {/* Contact Cards */}
                            <div className="grid sm:grid-cols-2 gap-6">
                                <div className="bg-gray-50 rounded-2xl p-6">
                                    <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center mb-4">
                                        <Phone className="w-6 h-6 text-primary-600" />
                                    </div>
                                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Phone</h3>
                                    <a href={`tel:${hospital?.phone || '+919999999999'}`} className="text-gray-600 hover:text-primary-600">
                                        {hospital?.phone || '+91 99999 99999'}
                                    </a>
                                </div>

                                <div className="bg-gray-50 rounded-2xl p-6">
                                    <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center mb-4">
                                        <Mail className="w-6 h-6 text-primary-600" />
                                    </div>
                                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Email</h3>
                                    <a href={`mailto:${hospital?.email || 'info@blinkeyehospital.com'}`} className="text-gray-600 hover:text-primary-600">
                                        {hospital?.email || 'info@blinkeyehospital.com'}
                                    </a>
                                </div>

                                <div className="bg-gray-50 rounded-2xl p-6 sm:col-span-2">
                                    <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center mb-4">
                                        <MapPin className="w-6 h-6 text-primary-600" />
                                    </div>
                                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Address</h3>
                                    <p className="text-gray-600">
                                        {hospital?.address || 'Mall Road, Amritsar, Punjab 143001'}
                                    </p>
                                </div>

                                <div className="bg-gray-50 rounded-2xl p-6 sm:col-span-2">
                                    <div className="w-12 h-12 bg-primary-100 rounded-xl flex items-center justify-center mb-4">
                                        <Clock className="w-6 h-6 text-primary-600" />
                                    </div>
                                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Working Hours</h3>
                                    <div className="text-gray-600 space-y-1 text-sm">
                                        <p>Mon - Fri: {hospital?.working_hours_weekday || '9:00 AM - 6:00 PM'}</p>
                                        {hospital?.working_hours_saturday && <p>Saturday: {hospital.working_hours_saturday}</p>}
                                        {hospital?.working_hours_sunday && <p className="text-red-500 font-medium">Sunday: {hospital.working_hours_sunday}</p>}
                                    </div>
                                </div>
                            </div>

                            {/* Map */}
                            <div className="bg-gray-50 rounded-2xl p-6">
                                <h3 className="text-lg font-semibold text-gray-900 mb-4">Find Us</h3>
                                <div className="aspect-video bg-gray-200 rounded-xl overflow-hidden">
                                    {hospital?.lat && hospital?.lng ? (
                                        <iframe
                                            src={hospital?.map_url || `https://www.openstreetmap.org/export/embed.html?bbox=${parseFloat(hospital.lng) - 0.015}%2C${parseFloat(hospital.lat) - 0.01}%2C${parseFloat(hospital.lng) + 0.015}%2C${parseFloat(hospital.lat) + 0.01}&layer=mapnik&marker=${hospital.lat}%2C${hospital.lng}`}
                                            width="100%"
                                            height="100%"
                                            style={{ border: 0 }}
                                            allowFullScreen=""
                                            loading="lazy"
                                            referrerPolicy="no-referrer-when-downgrade"
                                            title="Hospital Location"
                                        />
                                    ) : (
                                        <div className="w-full h-full flex items-center justify-center text-gray-400">
                                            <p>Map not available</p>
                                        </div>
                                    )}
                                </div>
                            </div>

                            {/* Emergency Contact */}
                            <div className={`bg-gradient-to-r ${hospital?.is_24_7_emergency ? 'from-red-500 to-red-600' : 'from-primary-500 to-primary-600'} rounded-2xl p-6 text-white`}>
                                <h3 className="text-lg font-semibold mb-2">{hospital?.is_24_7_emergency ? '24/7 Emergency' : 'Need Help?'}</h3>
                                <p className="opacity-90 mb-4">{hospital?.is_24_7_emergency ? 'Our emergency services are available round the clock' : 'Get in touch with our experts for any queries'}</p>
                                <a
                                    href={`tel:${hospital?.phone || '+919999999999'}`}
                                    className="inline-flex items-center gap-2 bg-white text-gray-900 font-semibold py-2 px-4 rounded-lg hover:bg-gray-50"
                                >
                                    <Phone className="w-5 h-5 text-primary-600" />
                                    {hospital?.is_24_7_emergency ? 'Emergency: ' : 'Call: '}{hospital?.phone || '+91 99999 99999'}
                                </a>
                            </div>
                        </motion.div>
                    </div>
                </div>
            </section>
        </div>
    );
}

// Blink_eye/resources/js/Pages/Frontend/Hospital/Contact.vue
<template>
  <HospitalLayout :hospital="hospital" :hospitals="hospitals">
    <!-- Emergency Contact Banner -->
    <div v-if="hospital.emergency_contact" class="bg-red-600 text-white py-3 px-4">
      <div class="container mx-auto flex flex-wrap items-center justify-center gap-4">
        <span class="font-bold">🚨 Emergency:</span>
        <a :href="`tel:${hospital.emergency_contact}`" class="font-semibold hover:underline">
          {{ hospital.emergency_contact }}
        </a>
        <span v-if="hospital.is_24_7_emergency" class="px-3 py-1 bg-white/20 rounded-full text-sm">
          24/7 Available
        </span>
      </div>
    </div>

    <!-- Header -->
    <section class="relative bg-gradient-to-r from-blue-900 to-blue-700 text-white py-16">
      <div class="absolute inset-0 bg-black/20"></div>
      <div class="relative container mx-auto px-4">
        <h1 class="text-4xl md:text-5xl font-bold mb-2">Contact Us</h1>
        <p class="text-xl opacity-90">Get in touch with {{ hospital.name }}</p>
      </div>
    </section>

    <!-- Breadcrumb -->
    <div class="bg-white border-b shadow-sm">
      <div class="container mx-auto px-4 py-3">
        <nav class="text-sm flex items-center gap-2">
          <Link href="/" class="text-blue-600 hover:underline">Home</Link>
          <span class="text-gray-400">/</span>
          <span class="text-gray-600">Contact Us</span>
        </nav>
      </div>
    </div>

    <!-- Contact Content -->
    <section class="py-16">
      <div class="container mx-auto px-4">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-12">
          
          <!-- Contact Information -->
          <div>
            <h2 class="text-2xl font-bold mb-6">Get in Touch</h2>
            
            <!-- Hospital Info Cards -->
            <div class="space-y-4 mb-8">
              <div class="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition border-l-4 border-blue-500">
                <div class="flex items-start gap-4">
                  <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <span class="text-xl">📍</span>
                  </div>
                  <div>
                    <h3 class="font-semibold mb-1">Address</h3>
                    <p class="text-gray-600">{{ hospital.address || 'Address not available' }}</p>
                    <p class="text-gray-600">{{ hospital.location?.name }}, India</p>
                  </div>
                </div>
              </div>

              <div class="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition border-l-4 border-blue-500">
                <div class="flex items-start gap-4">
                  <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <span class="text-xl">📞</span>
                  </div>
                  <div>
                    <h3 class="font-semibold mb-1">Phone</h3>
                    <a :href="`tel:${hospital.phone}`" class="text-gray-600 hover:text-blue-600">{{ hospital.phone }}</a>
                    <p v-if="hospital.emergency_contact" class="text-red-600 text-sm mt-1">
                      Emergency: {{ hospital.emergency_contact }}
                    </p>
                  </div>
                </div>
              </div>

              <div class="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition border-l-4 border-blue-500">
                <div class="flex items-start gap-4">
                  <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <span class="text-xl">✉️</span>
                  </div>
                  <div>
                    <h3 class="font-semibold mb-1">Email</h3>
                    <a :href="`mailto:${hospital.email}`" class="text-gray-600 hover:text-blue-600">{{ hospital.email }}</a>
                  </div>
                </div>
              </div>

              <div class="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition border-l-4 border-blue-500">
                <div class="flex items-start gap-4">
                  <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <span class="text-xl">🕐</span>
                  </div>
                  <div>
                    <h3 class="font-semibold mb-1">Working Hours</h3>
                    <p class="text-gray-600">Mon - Sat: {{ hospital.working_hours_weekday || '9:00 AM - 6:00 PM' }}</p>
                    <p v-if="hospital.working_hours_saturday" class="text-gray-600">Saturday: {{ hospital.working_hours_saturday }}</p>
                    <p v-if="hospital.working_hours_sunday" class="text-gray-600">Sunday: {{ hospital.working_hours_sunday }}</p>
                    <p v-if="hospital.is_24_7_emergency" class="text-red-600 font-semibold mt-2">🚨 24/7 Emergency Available</p>
                  </div>
                </div>
              </div>
            </div>

            <!-- Map -->
            <div class="bg-white p-6 rounded-xl shadow-sm">
              <h3 class="font-semibold mb-4">Find Us on Map</h3>
              <div class="h-64 bg-gray-100 rounded-lg overflow-hidden">
                <!-- OpenStreetMap Embed (No API key required) -->
                <iframe 
                  v-if="hospital.lat && hospital.lng"
                  width="100%" 
                  height="100%" 
                  style="border:0" 
                  loading="lazy"
                  referrerpolicy="no-referrer-when-downgrade"
                  :src="`https://www.openstreetmap.org/export/embed.html?bbox=${parseFloat(hospital.lng)-0.01}%2C${parseFloat(hospital.lat)-0.01}%2C${parseFloat(hospital.lng)+0.01}%2C${parseFloat(hospital.lat)+0.01}&layer=mapnik&marker=${hospital.lat}%2C${hospital.lng}`"
                >
                </iframe>
                <!-- Fallback to Google Maps web URL -->
                <div v-else-if="hospital.address" class="w-full h-full flex items-center justify-center">
                  <a 
                    :href="`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(hospital.address)}`"
                    target="_blank"
                    class="text-center p-4 hover:bg-gray-50 transition"
                  >
                    <span class="text-4xl block mb-2">🗺️</span>
                    <p class="text-gray-600">Click to open in Google Maps</p>
                  </a>
                </div>
                <div v-else class="w-full h-full flex items-center justify-center text-gray-400">
                  <div class="text-center">
                    <span class="text-4xl block mb-2">🗺️</span>
                    <p>Map not available</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Contact Form -->
          <div>
            <div class="bg-white p-8 rounded-xl shadow-lg">
              <h2 class="text-2xl font-bold mb-6">Send us a Message</h2>
              
              <div v-if="$page.props.flash?.success" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-6">
                {{ $page.props.flash.success }}
              </div>

              <form @submit.prevent="submitForm" class="space-y-6">
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">Full Name *</label>
                  <input 
                    v-model="form.name"
                    type="text" 
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    placeholder="Enter your full name"
                  />
                  <p v-if="errors.name" class="text-red-500 text-sm mt-1">{{ errors.name }}</p>
                </div>

                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">Email Address *</label>
                  <input 
                    v-model="form.email"
                    type="email" 
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    placeholder="Enter your email"
                  />
                  <p v-if="errors.email" class="text-red-500 text-sm mt-1">{{ errors.email }}</p>
                </div>

                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">Phone Number *</label>
                  <input 
                    v-model="form.phone"
                    type="tel" 
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    placeholder="Enter your phone number"
                  />
                  <p v-if="errors.phone" class="text-red-500 text-sm mt-1">{{ errors.phone }}</p>
                </div>

                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">Message *</label>
                  <textarea 
                    v-model="form.message"
                    rows="5" 
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    placeholder="How can we help you?"
                  ></textarea>
                  <p v-if="errors.message" class="text-red-500 text-sm mt-1">{{ errors.message }}</p>
                </div>

                <button 
                  type="submit" 
                  :disabled="loading"
                  class="w-full bg-blue-600 text-white py-3 px-6 rounded-lg font-semibold hover:bg-blue-700 transition disabled:opacity-50"
                >
                  {{ loading ? 'Sending...' : 'Send Message' }}
                </button>
              </form>
            </div>

            <!-- Quick Actions -->
            <div class="mt-6 bg-blue-50 p-6 rounded-xl">
              <h3 class="font-semibold mb-4">Quick Actions</h3>
              <div class="space-y-3">
                <Link 
                  href="/book-appointment" 
                  class="flex items-center gap-3 bg-white p-4 rounded-lg hover:shadow-md transition"
                >
                  <span class="text-2xl">📅</span>
                  <div>
                    <span class="font-medium block">Book an Appointment</span>
                    <span class="text-sm text-gray-500">Schedule a consultation</span>
                  </div>
                </Link>
                <a 
                  v-if="hospital.whatsapp"
                  :href="`https://wa.me/${hospital.whatsapp}`"
                  target="_blank"
                  class="flex items-center gap-3 bg-white p-4 rounded-lg hover:shadow-md transition"
                >
                  <span class="text-2xl">💬</span>
                  <div>
                    <span class="font-medium block">Chat on WhatsApp</span>
                    <span class="text-sm text-gray-500">Quick responses</span>
                  </div>
                </a>
                <a 
                  v-if="hospital.emergency_contact"
                  :href="`tel:${hospital.emergency_contact}`"
                  class="flex items-center gap-3 bg-red-50 p-4 rounded-lg hover:shadow-md transition border border-red-200"
                >
                  <span class="text-2xl">🚨</span>
                  <div>
                    <span class="font-medium block text-red-700">Emergency Contact</span>
                    <span class="text-sm text-red-600">{{ hospital.emergency_contact }}</span>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Other Locations -->
    <section class="py-8 bg-gray-100">
      <div class="container mx-auto px-4 text-center">
        <h3 class="font-semibold mb-4">Other Hospital Locations</h3>
        <div class="flex flex-wrap justify-center gap-3">
          <Link 
            v-for="h in hospitals" 
            :key="h.id"
            :href="h.slug ? `/${h.slug}` : '/'"
            class="bg-white px-4 py-2 rounded-lg text-gray-700 hover:text-blue-600 hover:shadow-sm transition"
          >
            {{ h.name }}
          </Link>
        </div>
      </div>
    </section>
  </HospitalLayout>
</template>

<script setup>
import { ref } from 'vue'
import { useForm } from '@inertiajs/vue3'
import HospitalLayout from '@/Layouts/HospitalLayout.vue'
import { Link } from '@inertiajs/vue3'

defineProps({
  hospital: Object,
  hospitals: Array,
  seo: Object
})

const loading = ref(false)
const errors = ref({})

const form = useForm({
  name: '',
  email: '',
  phone: '',
  message: ''
})

const submitForm = () => {
  loading.value = true
  errors.value = {}
  
  form.post('/contact', {
    onSuccess: () => {
      loading.value = false
      form.reset()
    },
    onError: (e) => {
      loading.value = false
      errors.value = e
    }
  })
}
</script>
